package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF007AFF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE5F1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF003E8A)
val md_theme_light_background = Color(0xFFF2F2F7)
val md_theme_light_onBackground = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF000000)
val md_theme_light_surfaceVariant = Color(0xFFFFFFFF)
val md_theme_light_onSurfaceVariant = Color(0xFF8E8E93)

val md_theme_dark_primary = Color(0xFF0A84FF)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF003258)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_background = Color(0xFF000000)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF1C1C1E)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF1C1C1E)
val md_theme_dark_onSurfaceVariant = Color(0xFF8E8E93)
val tokyo_night_primary = Color(0xFF7AA2F7)
val tokyo_night_onPrimary = Color(0xFF1A1B26)
val tokyo_night_primaryContainer = Color(0xFF3B4261)
val tokyo_night_onPrimaryContainer = Color(0xFFC0CAF5)
val tokyo_night_background = Color(0xFF1A1B26)
val tokyo_night_onBackground = Color(0xFFC0CAF5)
val tokyo_night_surface = Color(0xFF24283B)
val tokyo_night_onSurface = Color(0xFFC0CAF5)
val tokyo_night_surfaceVariant = Color(0xFF292E42)
val tokyo_night_onSurfaceVariant = Color(0xFFA9B1D6)
